app/mi_primer_app/urls.py
from django.contrib import admin
from django.urls import path

from app.mi_primer_app.views import AgregarArticulo, ListaArticulos, ModificarArticulo, VerArticulo

app_name = 'articulo'

urlpatterns = [
    path('', ListaArticulos.as_view() , name='ver-todos'),
    path('admin/', admin.site.urls),
    path('ver/<int:pk>/', VerArticulo.as_view(), name='detalle'),
    # path('eliminar/<int:pk>/', <vista>, name='eliminar'),
    path('agregar/', AgregarArticulo.as_view(), name='agregar'),
    path('modificar/<int:pk>/', ModificarArticulo.as_view(), name='modificar')
]

proyecto_1/urls.py
from django.conf import settings # faltaban estas importaciones
from django.conf.urls.static import static # faltaban estas importaciones

from django.contrib import admin
from django.urls import include, path

from proyecto_1.views import LoginUsuario, RegistrarUsuario, con_contenido_dinamico, inicio


urlpatterns = [
    path('', inicio, name="inicio"),
    path('admin/',admin.site.urls),
    path('usuario/registro/', RegistrarUsuario.as_view(), name='registro'),
    path('usuario/login/', LoginUsuario.as_view(), name="login"),
    path('con/', con_contenido_dinamico, name="prueba_1"),
    path('articulo/', include('app.mi_primer_app.urls')),
     # agregamos las rutas de mi aplicacion
]

if settings.DEBUG:  
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# agregamos estas lineas para poder servir los archivos estaticos y de media con el servidor en modo desarrollo

app/mi_primer_app/models.py
from encodings.punycode import T
from django.db import models
from django.urls import reverse_lazy

from app.usuario.models import Usuario

# Create your models here.
class Articulo(models.Model):
    id_articulo = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=50)
    subtitulo = models.CharField(max_length=100)
    contenido = models.TextField(max_length=5000)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    habilitado = models.BooleanField(default=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)
    imagen = models.ImageField(upload_to='articulos/', blank=True, null=True)

    def __str__(self):
        return f"{self.id_articulo} - Titulo: {self.titulo}"
    
    def url_articulo(self):
        return  reverse_lazy('articulo:detalle', kwargs={'pk':self.pk})


class Comentario(models.Model):
    articulo = models.ForeignKey(Articulo, on_delete=models.CASCADE, related_name="comentarios")
    autor = models.CharField(max_length=50, blank=True, null=True)
    contenido = models.TextField(max_length=1000)
    fecha = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"Comentario de {self.autor or 'Anónimo'} en {self.articulo.titulo}"

app/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser):

    dni = models.CharField(max_length=8, null=True, blank=True)
    foto_perfil = models.ImageField(upload_to='usuario/perfil/', null=True, blank=True)
    colaborador = models.BooleanField(default=False)
    
    @property
    def is_colaborador(self):
        return self.colaborador
    @property
    def is_admin(self):
        return self.is_superuser

    def __str__(self):
        return self.username

app/mi_primer_app/forms.py
from dataclasses import fields
from django import forms

from app.mi_primer_app.models import Articulo, Comentario


class ArticuloFormulario(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = ['titulo','subtitulo','contenido', 'imagen']

class ArticuloFormularioAdmin(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = ['titulo','subtitulo','contenido', 'imagen','habilitado']

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido']
   

proyecto_1/forms.py
from dataclasses import fields
from os import name
from django import forms
from django.contrib.auth.forms import UserCreationForm

from app.usuario.models import Usuario


class RegistrarUsuarioForm(UserCreationForm):

    email = forms.EmailField(required=True)
    
    class Meta:
        model = Usuario
        fields = ['username', 'first_name','last_name', 'email', 'password1', 'password2', 'foto_perfil']

app/mi_primer_app/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

from app.mi_primer_app.forms import ArticuloFormulario, ArticuloFormularioAdmin, ComentarioForm
from app.mi_primer_app.models import Articulo, Comentario

# Create your views here.

class ListaArticulos(ListView):
    model = Articulo
    template_name = 'hijo.html'
    context_object_name = 'articulos'

class VerArticulo(DetailView):
    model = Articulo
    template_name = 'detalle.html'
    context_object_name = 'articulo'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.articulo = self.object
            comentario.usuario = self.request.user
            comentario.save()
            return redirect("articulo:detalle", pk=self.object.pk)
        context = self.get_context_data()
        context["form_comentario"] = form
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_comentario'] = ComentarioForm()
        context['comentarios'] = self.object.comentarios.all()
        return context

class AgregarArticulo(UserPassesTestMixin, CreateView):
    model = Articulo
    template_name = 'agregar.html'
    form_class = ArticuloFormulario
    success_url = reverse_lazy('articulo:ver-todos')

    def test_func(self):
        return self.request.user.is_colaborador or self.request.user.is_superuser

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        titulo = form.instance.titulo
        if len(titulo) < 5:
            form.add_error("titulo", "El titulo debe tener al menos 5 caracteres")
            return self.form_invalid(form)
        return super().form_valid(form)

class ModificarArticulo(UserPassesTestMixin, UpdateView):

    def test_func(self):
        return self.request.user.is_authenticated and (self.request.user.is_superuser or self.get_object().usuario == self.request.user)

    model = Articulo
    template_name = 'agregar.html'
    form_class = ArticuloFormularioAdmin
    success_url = reverse_lazy('articulo:ver-todos')

app/usuario/views.py
from django.shortcuts import render

# Create your views here.

proyecto_1/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from app.mi_primer_app.models import Articulo
from django.views.generic import CreateView
from django.contrib.auth import login
from django.contrib.auth.views import LoginView

from proyecto_1.forms import RegistrarUsuarioForm

def inicio(request):
    contexto = {
        "titulo": "Pagina de prueba",
        "nombre": "Darian",
        "articulos": Articulo.objects.all()
    }
    return render(request,"base/base.html", contexto)


class RegistrarUsuario(CreateView):
    template_name = 'usuario/registro.html'
    form_class = RegistrarUsuarioForm
    success_url = reverse_lazy("inicio")

    def form_valid(self, form):
        usuario = form.save()
        login(self.request, usuario)
        return super().form_valid(form)

class LoginUsuario(LoginView):

    template_name = 'usuario/login.html'
    success_url = reverse_lazy('inicio')
    



def con_contenido_dinamico(request):
    contexto = {
        "titulo": "Pagina hijo",
        "nombre": "Darian",
        "articulos": Articulo.objects.all()
    }
    return render(request,"hijo.html", contexto)

templates/agregar.html
{% extends 'base/base.html' %}
{% load static %}

{% block titulo %}
{{ titulo }}
{% endblock %}

{% block contenido %}

<h3>Estoy reemplazando el contenido de mi padre</h3>
<p><strong>Titulo:</strong> Estoy escribiendo un titulo</p>

<h4><strong>AGREGAR ARTICULO:</strong></h4>

<form method="post" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {{ form.as_div }}

    <button type="submit" class="btn btn-success p-2">Cargar Articulo</button>
</form>

{% endblock %}

templates/base/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
        Hola {{ nombre }}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</head>
<style>
    form div{
        margin: 5px;
    }
</style>

<body>
    <header>
        <h1>Mi Sitio Django</h1>
        <nav>
            <a href="/">Volver</a>
            <a href="{% url 'prueba_1' %}">Contenido dinamico</a>
        </nav>
    </header>

    <main>
        {% block contenido %}
            Aca voy a poner el contenido dinamico en otras paginas.
        {% endblock %}
    </main>

    <footer>
        <p>© 2025 - Mi sitio en Django</p>
    </footer>
</body>
</html>

templates/comentario.html
{% load static %}



    

    
<form method="post" class="form">
    {% csrf_token %}
    {{ form.as_div }}
   
    <button type="submit" class="btn btn-success p-2">Comentar</button>

</form>

templates/detalle.html
{% extends 'base/base.html' %}
{% load static %}

{% block titulo %}
{{ titulo }}
{% endblock %}

{% block contenido %}

<h3>Estoy reemplazando el contenido de mi padre</h3>
<p><strong>Titulo:</strong> Estoy escribiendo un titulo</p>

<h4><strong>ARTICULO:</strong></h4>

{% if articulo.habilitado %}
<div class="card m-5">
    <div class="card-title m-2">
        <h5>{{ articulo.titulo }}</h5>
    </div>

    <img src="{{ articulo.imagen.url }} ">

    <div class="card-body m-2">

        <h6>{{ articulo.subtitulo }}</h6>
        <p><strong>Fecha creacion: </strong> {{ articulo.fecha_creacion }}</p>
        <hr>
        <p>{{ articulo.contenido }}</p>
        <a class="btn btn-warning" href="{% url 'articulo:modificar' articulo.id_articulo %}">Modificar</a>
        {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            {{ form_comentario.as_p }}
            <button type="submit" class="btn btn-success">Enviar comentario</button>
        </form>
        {% else %}
        <a href="{% url 'login' %}">
            <h3>Para comentar debe estar logueado</h3>
        </a>
        {% endif %}

    </div>
    <div class="card-footer">
        {% for comentario in comentarios %}
        <p>{{ comentario.autor }}: {{ comentario.contenido }}</p>
        {% if request.user.is_staff == True %}
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endif %}


{% endblock %}

templates/hijo.html
{% extends 'base/base.html' %}
{% load static %}

{% block titulo %}
{{ titulo }}
{% endblock %}

{% block contenido %}

<h3>Estoy reemplazando el contenido de mi padre</h3>
<p><strong>Titulo:</strong> Estoy escribiendo un titulo</p>

<h4><strong>ARTICULOS {{ titulo }}</strong></h4>
{% for articulo in articulos %}
{% if articulo.habilitado %}
<div class="card m-5">
    <div class="card-title m-2">
        <a href="{{ articulo.url_articulo }}">
            <h5>{{ articulo.titulo }}</h5>
        </a>
    </div>
    {% if articulo.imagen != None %}
    <img src="{{ articulo.imagen.url }}" style="max-height: 100px; width: 100%;">
    {% endif %}
    <div class="card-body m-2">

        <h6>{{ articulo.subtitulo }}</h6>
        <p><strong>Fecha creacion: </strong> {{ articulo.fecha_creacion }}</p>
        <hr>
    </div>
</div>
{% endif %}
{% endfor %}

{% if user.is_colaborador %}
<a href="{% url 'articulo:agregar' %}" class="btn btn-primary p-2">Crear articulo</a>
{% endif %}

{% endblock %}

templates/nieto.html
{% extends 'hijo.html' %}

templates/usuario/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block titulo %}
Login
{% endblock %}

{% block contenido %}

<h2>Login usuario</h2>

<form method="post">
    {% csrf_token %}
    <label for="username">Nombre de usuario:</label>
    <input id="username" name="username" placeholder="Ingrese aqui su nombre de usuario..." />
    <hr>
    <label for="password">Nombre de usuario:</label>
    <input type="password" name="password" id="password" placeholder="Ingrese aqui su contraseña..." />

    <button type="submit" class="btn btn-primary">Registrar</button>
</form>

{% endblock %}

templates/usuario/registro.html
{% extends 'base/base.html' %}
{% load static %}

{% block titulo %}
Registro de usuarios
{% endblock %}

{% block contenido %}

<h2>Crear usuario</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Registrar</button>
</form>

{% endblock %}